name: Sync Original Image

on:
  workflow_dispatch:

jobs:
  sync:
    runs-on: ubuntu-latest

    permissions:
      packages: write

    steps:
      - name: Login to ghcr.io
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Pull and Push
        run: |
          docker pull uncleluo/mous:latest
          docker tag uncleluo/mous:latest ghcr.io/${{ github.repository_owner }}/mous-backup:latest
          docker push ghcr.io/${{ github.repository_owner }}/mous-backup:latest
